# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import verification_pb2 as verification__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in verification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VerificationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Verify = channel.unary_unary(
                '/verification.VerificationService/Verify',
                request_serializer=verification__pb2.VerifyRequest.SerializeToString,
                response_deserializer=verification__pb2.JobHandle.FromString,
                _registered_method=True)
        self.GetVerifyStatus = channel.unary_unary(
                '/verification.VerificationService/GetVerifyStatus',
                request_serializer=verification__pb2.JobHandle.SerializeToString,
                response_deserializer=verification__pb2.VerifyResult.FromString,
                _registered_method=True)


class VerificationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVerifyStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=verification__pb2.VerifyRequest.FromString,
                    response_serializer=verification__pb2.JobHandle.SerializeToString,
            ),
            'GetVerifyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVerifyStatus,
                    request_deserializer=verification__pb2.JobHandle.FromString,
                    response_serializer=verification__pb2.VerifyResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verification.VerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verification.VerificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VerificationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verification.VerificationService/Verify',
            verification__pb2.VerifyRequest.SerializeToString,
            verification__pb2.JobHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVerifyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verification.VerificationService/GetVerifyStatus',
            verification__pb2.JobHandle.SerializeToString,
            verification__pb2.VerifyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoarseMatchingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RemineTile = channel.unary_unary(
                '/verification.CoarseMatchingService/RemineTile',
                request_serializer=verification__pb2.RemineRequest.SerializeToString,
                response_deserializer=verification__pb2.RemineResult.FromString,
                _registered_method=True)


class CoarseMatchingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RemineTile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoarseMatchingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RemineTile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemineTile,
                    request_deserializer=verification__pb2.RemineRequest.FromString,
                    response_serializer=verification__pb2.RemineResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verification.CoarseMatchingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verification.CoarseMatchingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoarseMatchingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RemineTile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verification.CoarseMatchingService/RemineTile',
            verification__pb2.RemineRequest.SerializeToString,
            verification__pb2.RemineResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
